### ISSUE TITLE
Latest version crashes if no internet connection

### ISSUE THREAD

**Issue by 097115** [achannarasappa/ticker#117]
**Describe the bug**
Crashes If launched w/o internet connection

**To Reproduce**
1. disconnect your internet connection
2. start `ticker`
3. see error:

             panic: interface conversion: interface {} is nil, not []string
            
            goroutine 1 [running]:
            github.com/achannarasappa/ticker/internal/currency.transformResponseCurrencyPairs(0x0, 0x0, 0x0, 0xc00002af70, 0x3, 0xc000114eb0, 0x1637b00, 0xc000238810)
                /home/runner/work/ticker/ticker/internal/currency/currency.go:78 +0x2df
            github.com/achannarasappa/ticker/internal/currency.getCurrencyPairSymbols(0x0, 0x0, 0xc000069ef0, 0xc000069f20, 0xc000069f50, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                /home/runner/work/ticker/ticker/internal/currency/currency.go:89 +0x385
            github.com/achannarasappa/ticker/internal/currency.GetCurrencyRates(0x0, 0x0, 0xc000069ef0, 0xc000069f20, 0xc000069f50, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                /home/runner/work/ticker/ticker/internal/currency/currency.go:98 +0xbf
            github.com/achannarasappa/ticker/internal/cli.getReference(0xa, 0xc00000cd60, 0x2, 0x2, 0xc000152480, 0x4, 0x4, 0x10101, 0x0, 0x0, ...)
                /home/runner/work/ticker/ticker/internal/cli/cli.go:114 +0xf2
            github.com/achannarasappa/ticker/internal/cli.GetContext(0x16466c0, 0x1937a40, 0xc000000f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                /home/runner/work/ticker/ticker/internal/cli/cli.go:72 +0x2a5
            github.com/achannarasappa/ticker/cmd.initConfig()
                /home/runner/work/ticker/ticker/cmd/root.go:57 +0x10a
            github.com/spf13/cobra.(*Command).preRun(0x18fcce0)
                /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:880 +0x49
            github.com/spf13/cobra.(*Command).execute(0x18fcce0, 0xc00001e1e0, 0x0, 0x0, 0x18fcce0, 0xc00001e1e0)
                /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:816 +0x14f
            github.com/spf13/cobra.(*Command).ExecuteC(0x18fcce0, 0x1044aaa, 0x18b4480, 0xc000048778)
                /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
            github.com/spf13/cobra.(*Command).Execute(...)
                /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
            github.com/achannarasappa/ticker/cmd.Execute()
                /home/runner/work/ticker/ticker/cmd/root.go:32 +0x31
            main.main()
                /home/runner/work/ticker/ticker/main.go:6 +0x25

**Expected behavior**
Should not crash. Can't say about other versions but 3.1.3-3.1.0 do crash for me, and 3.0.6 does not

 - OS: macOS 10.11
 - ticker Version: 3.1.0-3.1.3, may be some older, too.

**Additional context**
Happens to me when waking up the laptop (which may be quite slow sometimes while re-connecting to the wireless).

**Comment by stefaneacsu147** [comment]
It seems the issue was fixed in `3.14` - 8a8fd37796b3aae262e69348b80226a7594f647a release but it was not pushed yet.

**Comment by achannarasappa** [comment]
Thanks for reporting this issue

I've triggered the build and release for v3.1.4 now

**Comment by 097115** [comment]
@achannarasappa , @stefaneacsu147 Thanks for your replies, guys!

However, are you sure it fixes the issue?  I've just build the latest master (8a8fd37) myself, and if launched without the internet connection, it still crashes for me.

**Comment by achannarasappa** [comment]
Not sure if it would - the latest version addresses a different issue. I'll have to take a closer look later today

**Comment by 097115** [comment]
Thanks, Ani!

**Comment by stefaneacsu147** [comment]
It seems actually the issue was not fixed, I have upgraded right now to 3.1.4 and the issue persists.

**Comment by achannarasappa** [comment]
Should be fixed in v3.1.5 . New behavior is that ticker won't start if there's no network connection and report a useful error. Have a look when you get a chance and let me know if it's still occurring.

**Comment by 097115** [comment]
@achannarasappa 

Yeah, it's fixed now (also, after waking up from sleep and before the laptop connects to the wireless, it first goes empty, since has no data, and then, after the laptop does connect to the network, refreshes just fine, no more crashes).

Thanks again, closing this :)
